### ISSUE TITLE
Support for `plutus-script-utils`?

### ISSUE THREAD

**Issue by sourabhxyz** [txpipe/plutus-starter-kit#3]
Is it the case that the way things are, it's not possible to have some of modules defined in [`plutus-apps`](https://github.com/input-output-hk/plutus-apps) such as [`plutus-script-utils`](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-script-utils) to be present here?

**Comment by rvcas** [comment]
@sourabhxyz We intentionally tried to keep everything as minimal as possible but if you think this is useful I don't see why we shouldn't add this :)

**Comment by sourabhxyz** [comment]
@rvcas I am a beginner in Plutus, so my thought process in following might be wrong.

I think it's useful, as for instance, in the [current](https://github.com/txpipe/plutus-starter-kit/blob/main/src/Hello/Shared.hs#L28) code base, you have simplified version of [`mkUntypedValidator`](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-script-utils/src/Plutus/Script/Utils/V2/Typed/Scripts/Validators.hs#L92). 
Also `plutus-apps` contains `plutus-ledger`, which has some useful types like `PubKeyHash`, `PaymentPubKeyHash`, etc.
So, I think support for `plutus-apps` is essential but once again, excuse my noobness.

**Comment by sourabhxyz** [comment]
I believe, our `.cabal` file can be minimal but `cabal.project` file should be rich enough so that one can add these things in build dependency if required.

**Comment by rvcas** [comment]
@sourabhxyz that makes sense to me

cc @scarmuega

**Comment by scarmuega** [comment]
yeah, makes sense, thanks for bringing it up @sourabhxyz.
`plutus-script-utils` was recently added as part of #13
