### ISSUE TITLE
Unlock Funds steps not working

### ISSUE THREAD

**Issue by aortizpimentel** [txpipe/plutus-starter-kit#8]
Hi, Unlock Funds steps have some errors:

Typo
 `  --tx-in ${lockedtxin} `

Should be:
  `  --tx-in ${locktxin} \`

----------

Wrong Path
 `  --change-address $(cat /assets/wallet1.addr) \`

Should be
`  --change-address $(cat assets/wallet1.addr) \`

----------

Wrong Path
`  --protocol-params-file params.json \
`
Should be
`  --protocol-params-file assets/params.json \
`

----------

Missing variable
`  --tx-in-collateral ${collateraltxin} \
`

It should be created as well as we did for "locktxin"

**Comment by scarmuega** [comment]
thanks @aortizpimentel, good catch!
all of the above have been addressed in recent PRs.
